version: "3.8"
services:
  server: 
    container_name: fortune_server
    image: philipl1/fortune_server # -t 
    build: ./service-1
    # deploy:
    #   replicas: 5
    ports:
    - target: 5000 #container 
      published: 5000 #host 
      protocol: tcp
    environment: 
      DATABASE_URI: ${DATABASE_URI}
  day_api:
    container_name: day_api
    image: philipl1/day_api
    build: ./service-3
  number_api: 
    container_name: number_api
    image: philipl1/number_api
    build: ./service-2
  fortune_api: 
    container_name: fortune_api
    image: philipl1/fortune_api
    build: ./service-4
    # deploy:
    #   replicas: 5
 