version: "3.8"
services:
  server: 
    container_name: fortune-server
    image: philipl1/fortune-server # -t 
    build: ./service-1
    # deploy:
    #   replicas: 5
    ports:
    - target: 5000 #container 
      published: 5000 #host 
      protocol: tcp
    environment: 
      DATABASE_URI: ${DATABASE_URI}
  day_api:
    container_name: day-api
    image: philipl1/day-api
    build: ./service-3
  number_api: 
    container_name: number-api
    image: philipl1/number-api
    build: ./service-2
  fortune_api: 
    container_name: fortune-api
    image: philipl1/fortune-api
    build: ./service-4
    # deploy:
    #   replicas: 5
 