apiVersion: v1
kind: Service
metadata:
  name: fortune-api
spec:
  selector:
    app: fortune-api
  ports: 
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-api
  labels: 
    app: fortune-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortune-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25% # how many containers can be spun up at a given time 
      maxUnavailable: 25% # how many of the containers can be brought down at a given down 
  template:
    metadata:
      labels:
        app: fortune-api
    spec:
      containers:
      - name: fortune-api
        image: philipl1/fortune-api:latest
        ports:
        - containerPort: 5000

              
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"