apiVersion: v1
kind: Service
metadata:
  name: number-api
spec:
  selector:
    app: number-api
  ports: 
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: number-api
  labels: 
    app: number-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: number-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25% 
  template:
    metadata:
      labels:
        app: number-api
    spec:
      containers:
      - name: number-api
        image: philipl1/number-api:latest
        ports:
        - containerPort: 5000
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"