---
# tasks file for nginx
- name: install nginx
  apt:
    name: nginx
    state: present
    update_cache: true

#template file into machine find nginx and put it here
- name: Template a file to /etc/file.conf
  template:
   src: nginx.conf
   dest: /etc/nginx.conf
  register: nginx_config

#reload nginx
- name: Restart nginx if needed 
  service:
    name: nginx
    state: restarted
  when: nginx_config.changed


