- hosts: 
  - managers
  - workers
  become: true
  roles:
  - install-docker 

- hosts: managers
  become: true 
  roles:
  - swarm-manager

- hosts: workers
  become: true 
  roles:
  - swarm-worker

- hosts: load_balance
  become: true 
  roles:
  - nginx 
 









# - hosts: all
#   become: true 
#   tasks:
#   - name: "Install dependencies"
#   apt: 
#   - name "install NGINX"
#   apt:
#     name: "nginx"
#     state: present
#     update_cache: true 
#   - name: "Copy nginx.conf over"
#     copy:
#       src: nginc.conf
#       dest: .etc/nginx/nginx.xonf
#     register: nginx_config
#   - name: "Print ngnix stuff"
#     debug:
#       msg: "{{ nginx_config }}"
#   - name: "Restart nginx if needed"
#     service:
#       name: nginx 
#       state: restarted
#     when: nginx_config.changed == true 




