---
# tasks file for swarm-manager
- name: "Init a new swarm" 
  docker_swarm:
    state: present 

- name: "Get info on Docker swarm" 
  docker_swarm_info:
  register: swarm_info

- name: Add to docker group
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker

  

# - name: "show info"
#   debug:
#     msg: "{{ swarm_info }}"
